apiVersion: v1
kind: Service
metadata:
  name: grpc-calculator-service
  namespace: default
spec:
  selector:
    k8s-app: grpc-calculator-app
  ports:
  - port: 50051
    targetPort: 50051
    name: grpc