apiVersion: v1
kind: Service
metadata:
  name: grpc-calculator-servicee
  namespace: default
spec:
  selector:
    k8s-app: grpc-calculator-appp
  ports:
  - port: 50051
    targetPort: 50051
    name: grpc